encoding: UTF-8
# Site settings
title: Thomas Sch&uuml;hly
description: DHBW_Scrape
baseurl: "/"
url: "thaiminater.github.io/DHBW_Scrape/" #

# User settings
username: Thomas Sch√ºhly
email: thomas.schuehly@outlook.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
